server.port=9092
server.address=0.0.0.0
spring.application.name=servicio-reportes

# --- JWT ---
jwt.issuer=andinatrading-auth
jwt.secret=${JWT_SECRET}

# --- Integraciones internas ---
catalogos.base-url=http://servicio-catalogos:8082
inversionistas.base-url=http://servicio-inversionista:8083
comisionistas.base-url=http://servicio-comisionista:8084
ordenes.base-url= http://servicio-ordenes:8087
