server.port=8084
server.address=0.0.0.0
spring.application.name=servicio-comisionista

# --- Datasource (MySQL) ---
spring.datasource.url=jdbc:mysql://${DB_HOST:${HOST_DOCKER_INTERNAL:host.docker.internal}}:${DB_PORT:3306}/${DB_NAME_COMISIONISTAS}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# --- Flyway ---
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# --- JWT ---
jwt.issuer=andinatrading-auth
jwt.secret=${JWT_SECRET}

# --- Feign ---
auth.base-url=http://servicio-autenticacion:8081
catalogos.base-url=http://servicio-catalogos:8082

# --- Logs ---
logging.level.org.springframework.security=INFO
logging.level.co.edu.unbosque.foresta=INFO

# --------- Integraciones internas ---------
auditoria.base-url= http://servicio-auditoria:9090
