server.port=9091
server.address=0.0.0.0
spring.application.name=servicio-respaldo

# --------- JWT ---------
jwt.issuer=andinatrading-auth
jwt.secret=${JWT_SECRET}

# --------- Logs ---------
logging.level.org.springframework.security=WARN
logging.level.co.edu.unbosque.foresta=INFO

# --------- BD ---------
app.backup.dir=/opt/foresta/backups
app.backup.host=${DB_HOST:${HOST_DOCKER_INTERNAL:host.docker.internal}}
app.backup.port=${DB_PORT:3306}
app.backup.user=${DB_USER}
app.backup.password=${DB_PASS}
app.backup.databases=andinatrading_auth,andinatrading_catalogos,andinatrading_inversionistas,andinatrading_comisionistas,andinatrading_contratos,andinatrading_cuentas,andinatrading_ordenes,andinatrading_auditoria

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
spring.data.jpa.repositories.enabled=false
spring.flyway.enabled=false



