# --------- Server ---------
server.port=8088
server.address=0.0.0.0
spring.application.name=servicio-portafolio

# --------- JWT ---------
jwt.issuer=andinatrading-auth
jwt.secret=${JWT_SECRET}

# --------- Logging ---------
logging.level.org.springframework.security=WARN
logging.level.co.edu.unbosque.foresta=INFO

# --------- Market ---------
alpaca.market.base-url=https://data.alpaca.markets
alpaca.market.api-key-id=${APCA_API_KEY_ID_MARKET}
alpaca.market.api-secret-key=${APCA_API_SECRET_KEY_MARKET}
marketdata.default.feed=iex
marketdata.default.watchlist=AAPL,MSFT,NVDA

