server.port=8080
spring.application.name=api-gateway
spring.profiles.active=docker

# Actuator
management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.gateway.enabled=true

# JWT
security.jwt.secret=${JWT_SECRET}

# CORS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true

# ===== ROUTES =====
# 0) AUTH
spring.cloud.gateway.routes[0].id=auth
spring.cloud.gateway.routes[0].uri=http://servicio-autenticacion:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

# 1) CATALOGOS
spring.cloud.gateway.routes[1].id=catalogos
spring.cloud.gateway.routes[1].uri=http://servicio-catalogos:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/catalogos/**
spring.cloud.gateway.routes[1].filters[0].name=JwtAuth

# 2) INVERSIONISTA
spring.cloud.gateway.routes[2].id=inversionista
spring.cloud.gateway.routes[2].uri=http://servicio-inversionista:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/inversionistas/**
spring.cloud.gateway.routes[2].filters[0].name=JwtAuth

# 3) COMISIONISTAS
spring.cloud.gateway.routes[3].id=comisionistas
spring.cloud.gateway.routes[3].uri=http://servicio-comisionista:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/comisionistas/**
spring.cloud.gateway.routes[3].filters[0].name=JwtAuth

# 4) CONTRATOS
spring.cloud.gateway.routes[4].id=contratos
spring.cloud.gateway.routes[4].uri=http://servicio-contratos:8085
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/contratos/**
spring.cloud.gateway.routes[4].filters[0].name=JwtAuth

# 5) CUENTAS
spring.cloud.gateway.routes[5].id=cuentas
spring.cloud.gateway.routes[5].uri=http://servicio-cuentas:8086
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/cuentas/**
spring.cloud.gateway.routes[5].filters[0].name=JwtAuth

# 6) ORDENES
spring.cloud.gateway.routes[6].id=ordenes
spring.cloud.gateway.routes[6].uri=http://servicio-ordenes:8087
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/ordenes/**,/api/mercado/**,/api/saldo/**
spring.cloud.gateway.routes[6].filters[0].name=JwtAuth

# 7) PORTAFOLIO / MARKETDATA
spring.cloud.gateway.routes[7].id=portafolio
spring.cloud.gateway.routes[7].uri=http://servicio-portafolio:8088
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/market/**
spring.cloud.gateway.routes[7].filters[0].name=JwtAuth



# Logs
logging.level.org.springframework.security=WARN
logging.level.org.springframework.cloud.gateway=INFO
